In [1]:
# Import libraries
import os
import glob
from osgeo import gdal
import numpy as np
import numpy.ma as ma
import matplotlib.pyplot as plt
import scipy.ndimage
import pandas as pd
import datetime as dt
import rasterio as rio
import re
import geopandas as gpd
import earthpy as et
import earthpy.plot as ep
import earthpy.spatial as es
import earthpy.mask as em
from pyhdf.SD import SD, SDC
import pprint
import gdal
from gdalconst import *
import matplotlib.colors as colors 
from mpl_toolkits.axes_grid1 import make_axes_locatable

In [2]:
# Set input directory, and change working directory - plug in D:
inDir = "D:\\masters_data\\output\\csv\\NDVI\\Total\\Data"   
os.chdir(inDir)                                                               # Change to working directory
outDir = os.path.normpath(os.path.split(inDir)[0] + os.sep + 'output') + '\\' # Create and set output directory
if not os.path.exists(outDir): os.makedirs(outDir)
VI_data = glob.glob('*MOD13*')
print(len(VI_data))

1648

In [3]:
H19V08_VI_data = glob.glob('*h19v08*')
NUMBER = 0

H19V08_VI_array = np.zeros((2400, 2400))
for i in range(len(H19V08_VI_data)):
    file = pd.read_csv(H19V08_VI_data[NUMBER], header= None)
    H19V08_VI_array += file
    NUMBER += 1

In [4]:
average_H19V08_VI_array = H19V08_VI_array / len(H19V08_VI_data)

In [5]:
np.savetxt("D:\\masters_data\\output\csv\\NDVI\Total\\H19V08_VI_array.csv", average_H19V08_VI_array, delimiter=",", fmt='%s')

In [6]:
average_H19V08_VI_array

,0,1,2,3,4,5,6,7,8,9,...,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399
0,4521.393204,4599.332524,4494.378641,4429.266990,4441.665049,4551.786408,4818.665049,4872.449029,4662.313107,4649.116505,...,4714.531553,5035.145631,4975.820388,5005.213592,5062.475728,5091.315534,5099.148058,4747.441748,4545.271845,4484.633495
1,4668.927184,4667.084951,4496.196602,4370.058252,4399.907767,4599.279126,4799.616505,4775.966019,4630.689320,4531.133495,...,4863.512136,4971.021845,4835.922330,4951.182039,5064.507282,5079.708738,4890.849515,4713.031553,4554.956311,4427.160194
2,4777.393204,4725.885922,4524.242718,4321.781553,4405.480583,4561.919903,4765.973301,4717.793689,4387.737864,4274.080097,...,4997.516990,5018.740291,5081.742718,5150.949029,5135.298544,4913.638350,4612.725728,4474.526699,4382.266990,4301.250000
3,4776.308252,4798.796117,4623.223301,4425.050971,4471.592233,4703.135922,4701.055825,4573.694175,4475.919903,4349.514563,...,5001.317961,5043.623786,4905.203883,4831.558252,4745.764563,4482.815534,4276.975728,4230.728155,4177.356796,4137.286408
4,4714.495146,4742.155340,4703.043689,4600.893204,4468.885922,4642.492718,4686.956311,4553.750000,4528.429612,4488.898058,...,4759.817961,4792.861650,4640.439320,4555.631068,4457.611650,4277.240291,4182.182039,4139.033981,4145.439320,4190.563107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,4830.723301,4853.155340,4848.186893,4749.131068,4707.813107,4852.575243,4906.194175,4882.104369,4821.885922,4755.038835,...,7657.524272,7642.570388,7696.667476,7717.060680,7718.900485,7725.186893,7811.327670,7782.949029,7840.733010,7773.876214
2396,4846.628641,5063.902913,4893.922330,4897.152913,4770.987864,4910.082524,4914.490291,4919.905340,4916.293689,4959.759709,...,7631.118932,7587.150485,7682.055825,7729.893204,7696.075243,7783.927184,7900.949029,7822.779126,7878.531553,7839.597087
2397,4911.296117,5101.759709,5040.834951,5033.269417,5010.182039,4891.737864,4916.082524,4850.332524,4803.970874,4743.495146,...,7650.808252,7590.769417,7634.152913,7725.720874,7823.650485,7778.412621,7886.315534,7850.997573,7812.269417,7801.859223
2398,4898.735437,4985.385922,5132.031553,5214.885922,5100.065534,4949.165049,4892.645631,4799.172330,4644.507282,4681.359223,...,7721.961165,7655.262136,7602.686893,7696.189320,7731.000000,7813.708738,7817.733010,7801.456311,7748.655340,7791.303398
2399,4848.296117,5084.281553,5136.094660,5069.946602,5003.655340,4850.723301,4821.332524,4828.733010,4832.893204,4687.359223,...,7742.682039,7724.657767,7698.041262,7638.417476,7650.601942,7770.701456,7757.507282,7791.191748,7747.148058,7751.019417