In [1]:
import math
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import numpy.ma as ma
import pandas as pd
import datetime as dt
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as colors 
from mpl_toolkits.axes_grid1 import make_axes_locatable 
import cartopy.crs as ccrs
import cartopy.crs as crs
import cartopy.feature as cfeature
import h5py  
from astropy.time import Time
import os
import glob
from osgeo import gdal
import scipy.ndimage
import rasterio as rio
import re
import geopandas as gpd
import earthpy as et
import earthpy.plot as ep
import earthpy.spatial as es
import earthpy.mask as em
from pyhdf.SD import SD, SDC
import pprint
import csv

In [3]:
# Set input directory, and change working directory - plug in D:
inDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H19V07"  # I should change this so I can work from github?
os.chdir(inDir)  # Change to working directory
outDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H19V07" # Create and set output directory
if not os.path.exists(outDir): os.makedirs(outDir)

In [4]:
# select first rainfall file
H19V07_2002 = glob.glob('*2002*')
H19V07_2002 = pd.read_csv(H19V07_2002[0], header = None)
H19V07_2003 = glob.glob('*2003*')
H19V07_2003 = pd.read_csv(H19V07_2003[0], header = None)
H19V07_2004 = glob.glob('*2004*')
H19V07_2004 = pd.read_csv(H19V07_2004[0], header = None)
H19V07_2005 = glob.glob('*2005*')
H19V07_2005 = pd.read_csv(H19V07_2005[0], header = None)
H19V07_2006 = glob.glob('*2006*')
H19V07_2006 = pd.read_csv(H19V07_2006[0], header = None)
H19V07_2007 = glob.glob('*2007*')
H19V07_2007 = pd.read_csv(H19V07_2007[0], header = None)
H19V07_2008 = glob.glob('*2008*')
H19V07_2008 = pd.read_csv(H19V07_2008[0], header = None)
H19V07_2009 = glob.glob('*2009*')
H19V07_2009 = pd.read_csv(H19V07_2009[0], header = None)
H19V07_2010 = glob.glob('*2010*')
H19V07_2010 = pd.read_csv(H19V07_2010[0], header = None)
H19V07_2011 = glob.glob('*2011*')
H19V07_2011 = pd.read_csv(H19V07_2011[0], header = None)
H19V07_2012 = glob.glob('*2012*')
H19V07_2012 = pd.read_csv(H19V07_2012[0], header = None)
H19V07_2013 = glob.glob('*2013*')
H19V07_2013 = pd.read_csv(H19V07_2013[0], header = None)
H19V07_2014 = glob.glob('*2014*')
H19V07_2014 = pd.read_csv(H19V07_2014[0], header = None)
H19V07_2015 = glob.glob('*2015*')
H19V07_2015 = pd.read_csv(H19V07_2015[0], header = None)
H19V07_2016 = glob.glob('*2016*')
H19V07_2016 = pd.read_csv(H19V07_2016[0], header = None)
H19V07_2017 = glob.glob('*2017*')
H19V07_2017 = pd.read_csv(H19V07_2017[0], header = None)
H19V07_2018 = glob.glob('*2018*')
H19V07_2018 = pd.read_csv(H19V07_2018[0], header = None)
H19V07_2019 = glob.glob('*2019*')
H19V07_2019 = pd.read_csv(H19V07_2019[0], header = None)

# also need coordinates
H19V07_coordinates = pd.read_csv("D:\masters_data\output\csv\Rainfall\Rainfall_coordinates\H19V07.csv", header = None)

In [5]:
# 2002
H19V07_2002 = H19V07_2002.to_numpy()
H19V07_2002 = H19V07_2002.flatten().tolist()

# 2003
H19V07_2003 = H19V07_2003.to_numpy()
H19V07_2003 = H19V07_2003.flatten().tolist()

# 2004
H19V07_2004 = H19V07_2004.to_numpy()
H19V07_2004 = H19V07_2004.flatten().tolist()

# 2005
H19V07_2005 = H19V07_2005.to_numpy()
H19V07_2005 = H19V07_2005.flatten().tolist()

# 2006
H19V07_2006 = H19V07_2006.to_numpy()
H19V07_2006 = H19V07_2006.flatten().tolist()

# 2007
H19V07_2007 = H19V07_2007.to_numpy()
H19V07_2007 = H19V07_2007.flatten().tolist()

# 2008
H19V07_2008 = H19V07_2008.to_numpy()
H19V07_2008 = H19V07_2008.flatten().tolist()

# 2009
H19V07_2009 = H19V07_2009.to_numpy()
H19V07_2009 = H19V07_2009.flatten().tolist()

# 2010
H19V07_2010 = H19V07_2010.to_numpy()
H19V07_2010 = H19V07_2010.flatten().tolist()

# 2011
H19V07_2011 = H19V07_2011.to_numpy()
H19V07_2011 = H19V07_2011.flatten().tolist()

# 2012
H19V07_2012 = H19V07_2012.to_numpy()
H19V07_2012 = H19V07_2012.flatten().tolist()

# 2013
H19V07_2013 = H19V07_2013.to_numpy()
H19V07_2013 = H19V07_2013.flatten().tolist()

# 2014
H19V07_2014 = H19V07_2014.to_numpy()
H19V07_2014 = H19V07_2014.flatten().tolist()

# 2015
H19V07_2015 = H19V07_2015.to_numpy()
H19V07_2015 = H19V07_2015.flatten().tolist()

# 2016
H19V07_2016 = H19V07_2016.to_numpy()
H19V07_2016 = H19V07_2016.flatten().tolist()

# 2017
H19V07_2017 = H19V07_2017.to_numpy()
H19V07_2017 = H19V07_2017.flatten().tolist()

# 2011
H19V07_2018 = H19V07_2018.to_numpy()
H19V07_2018 = H19V07_2018.flatten().tolist()

# 2011
H19V07_2019 = H19V07_2019.to_numpy()
H19V07_2019 = H19V07_2019.flatten().tolist()

In [8]:
H19V07_latitude = H19V07_coordinates[0]
H19V07_longitude = H19V07_coordinates[1]

In [10]:
print(len(H19V07_latitude))
print(len(H19V07_2019))

5760000
5760000

In [12]:
columns = {'latitude': H19V07_latitude, 'longitude': H19V07_longitude, '2002': H19V07_2002, '2003': H19V07_2003,
        '2004': H19V07_2004, '2005': H19V07_2005, '2006': H19V07_2006, '2007': H19V07_2007,
        '2008': H19V07_2008, '2009': H19V07_2009, '2010': H19V07_2010, '2011': H19V07_2011,
        '2012': H19V07_2012, '2013': H19V07_2013, '2014': H19V07_2014, '2015': H19V07_2015,
        '2016': H19V07_2016, '2017': H19V07_2017, '2018': H19V07_2018, '2019': H19V07_2019}

In [13]:
data = pd.DataFrame(data=columns)

In [14]:
data

,latitude,longitude,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,20.0,10.65,8.957365,15.961897,5.378073,32.918410,17.953107,6.078772,9.790865,31.036372,23.737983,38.602676,51.206720,32.745213,19.946145,18.127511,24.663130,26.711744,35.743338,16.347299
1,20.0,10.65,8.957365,15.961897,5.378073,32.918410,17.953107,6.078772,9.790865,31.036372,23.737983,38.602676,51.206720,32.745213,19.946145,18.127511,24.663130,26.711744,35.743338,16.347299
2,20.0,10.65,8.957365,15.961897,5.378073,32.918410,17.953107,6.078772,9.790865,31.036372,23.737983,38.602676,51.206720,32.745213,19.946145,18.127511,24.663130,26.711744,35.743338,16.347299
3,20.0,10.65,8.957365,15.961897,5.378073,32.918410,17.953107,6.078772,9.790865,31.036372,23.737983,38.602676,51.206720,32.745213,19.946145,18.127511,24.663130,26.711744,35.743338,16.347299
4,20.0,10.65,8.957365,15.961897,5.378073,32.918410,17.953107,6.078772,9.790865,31.036372,23.737983,38.602676,51.206720,32.745213,19.946145,18.127511,24.663130,26.711744,35.743338,16.347299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5759995,10.0,20.30,743.113831,905.061331,902.496610,852.565335,1088.688577,891.605672,906.535666,705.369450,900.077195,814.681243,1027.385552,762.652186,1001.326656,898.811270,1088.884885,1041.749171,994.524723,958.345995
5759996,10.0,20.30,743.113831,905.061331,902.496610,852.565335,1088.688577,891.605672,906.535666,705.369450,900.077195,814.681243,1027.385552,762.652186,1001.326656,898.811270,1088.884885,1041.749171,994.524723,958.345995
5759997,10.0,20.30,743.113831,905.061331,902.496610,852.565335,1088.688577,891.605672,906.535666,705.369450,900.077195,814.681243,1027.385552,762.652186,1001.326656,898.811270,1088.884885,1041.749171,994.524723,958.345995
5759998,10.0,20.30,743.113831,905.061331,902.496610,852.565335,1088.688577,891.605672,906.535666,705.369450,900.077195,814.681243,1027.385552,762.652186,1001.326656,898.811270,1088.884885,1041.749171,994.524723,958.345995
5759999,10.0,20.30,743.113831,905.061331,902.496610,852.565335,1088.688577,891.605672,906.535666,705.369450,900.077195,814.681243,1027.385552,762.652186,1001.326656,898.811270,1088.884885,1041.749171,994.524723,958.345995

In [15]:
np.savetxt("D:\\masters_data\\output\\csv\\Rainfall\\Trendmaps\\Complete_dataframes\\H19V07_rainfall_data.csv", data, delimiter=",")

In [16]:
# Set input directory, and change working directory - plug in D:
inDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H19V08"  # I should change this so I can work from github?
os.chdir(inDir)  # Change to working directory
outDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H19V08" # Create and set output directory
if not os.path.exists(outDir): os.makedirs(outDir)
    
# select first rainfall file
H19V08_2002 = glob.glob('*2002*')
H19V08_2002 = pd.read_csv(H19V08_2002[0], header = None)
H19V08_2003 = glob.glob('*2003*')
H19V08_2003 = pd.read_csv(H19V08_2003[0], header = None)
H19V08_2004 = glob.glob('*2004*')
H19V08_2004 = pd.read_csv(H19V08_2004[0], header = None)
H19V08_2005 = glob.glob('*2005*')
H19V08_2005 = pd.read_csv(H19V08_2005[0], header = None)
H19V08_2006 = glob.glob('*2006*')
H19V08_2006 = pd.read_csv(H19V08_2006[0], header = None)
H19V08_2007 = glob.glob('*2007*')
H19V08_2007 = pd.read_csv(H19V08_2007[0], header = None)
H19V08_2008 = glob.glob('*2008*')
H19V08_2008 = pd.read_csv(H19V08_2008[0], header = None)
H19V08_2009 = glob.glob('*2009*')
H19V08_2009 = pd.read_csv(H19V08_2009[0], header = None)
H19V08_2010 = glob.glob('*2010*')
H19V08_2010 = pd.read_csv(H19V08_2010[0], header = None)
H19V08_2011 = glob.glob('*2011*')
H19V08_2011 = pd.read_csv(H19V08_2011[0], header = None)
H19V08_2012 = glob.glob('*2012*')
H19V08_2012 = pd.read_csv(H19V08_2012[0], header = None)
H19V08_2013 = glob.glob('*2013*')
H19V08_2013 = pd.read_csv(H19V08_2013[0], header = None)
H19V08_2014 = glob.glob('*2014*')
H19V08_2014 = pd.read_csv(H19V08_2014[0], header = None)
H19V08_2015 = glob.glob('*2015*')
H19V08_2015 = pd.read_csv(H19V08_2015[0], header = None)
H19V08_2016 = glob.glob('*2016*')
H19V08_2016 = pd.read_csv(H19V08_2016[0], header = None)
H19V08_2017 = glob.glob('*2017*')
H19V08_2017 = pd.read_csv(H19V08_2017[0], header = None)
H19V08_2018 = glob.glob('*2018*')
H19V08_2018 = pd.read_csv(H19V08_2018[0], header = None)
H19V08_2019 = glob.glob('*2019*')
H19V08_2019 = pd.read_csv(H19V08_2019[0], header = None)

In [17]:
# also need coordinates
H19V08_coordinates = pd.read_csv("D:\masters_data\output\csv\Rainfall\Rainfall_coordinates\H19V08.csv", header = None)
H19V08_latitude = H19V08_coordinates[0]
H19V08_longitude = H19V08_coordinates[1]

In [18]:
# 2002
H19V08_2002 = H19V08_2002.to_numpy()
H19V08_2002 = H19V08_2002.flatten().tolist()

# 2003
H19V08_2003 = H19V08_2003.to_numpy()
H19V08_2003 = H19V08_2003.flatten().tolist()

# 2004
H19V08_2004 = H19V08_2004.to_numpy()
H19V08_2004 = H19V08_2004.flatten().tolist()

# 2005
H19V08_2005 = H19V08_2005.to_numpy()
H19V08_2005 = H19V08_2005.flatten().tolist()

# 2006
H19V08_2006 = H19V08_2006.to_numpy()
H19V08_2006 = H19V08_2006.flatten().tolist()

# 2007
H19V08_2007 = H19V08_2007.to_numpy()
H19V08_2007 = H19V08_2007.flatten().tolist()

# 2008
H19V08_2008 = H19V08_2008.to_numpy()
H19V08_2008 = H19V08_2008.flatten().tolist()

# 2009
H19V08_2009 = H19V08_2009.to_numpy()
H19V08_2009 = H19V08_2009.flatten().tolist()

# 2010
H19V08_2010 = H19V08_2010.to_numpy()
H19V08_2010 = H19V08_2010.flatten().tolist()

# 2011
H19V08_2011 = H19V08_2011.to_numpy()
H19V08_2011 = H19V08_2011.flatten().tolist()

# 2012
H19V08_2012 = H19V08_2012.to_numpy()
H19V08_2012 = H19V08_2012.flatten().tolist()

# 2013
H19V08_2013 = H19V08_2013.to_numpy()
H19V08_2013 = H19V08_2013.flatten().tolist()

# 2014
H19V08_2014 = H19V08_2014.to_numpy()
H19V08_2014 = H19V08_2014.flatten().tolist()

# 2015
H19V08_2015 = H19V08_2015.to_numpy()
H19V08_2015 = H19V08_2015.flatten().tolist()

# 2016
H19V08_2016 = H19V08_2016.to_numpy()
H19V08_2016 = H19V08_2016.flatten().tolist()

# 2017
H19V08_2017 = H19V08_2017.to_numpy()
H19V08_2017 = H19V08_2017.flatten().tolist()

# 2011
H19V08_2018 = H19V08_2018.to_numpy()
H19V08_2018 = H19V08_2018.flatten().tolist()

# 2011
H19V08_2019 = H19V08_2019.to_numpy()
H19V08_2019 = H19V08_2019.flatten().tolist()

In [20]:
columns = {'latitude': H19V08_latitude, 'longitude': H19V08_longitude, '2002': H19V08_2002, '2003': H19V08_2003,
        '2004': H19V08_2004, '2005': H19V08_2005, '2006': H19V08_2006, '2007': H19V08_2007,
        '2008': H19V08_2008, '2009': H19V08_2009, '2010': H19V08_2010, '2011': H19V08_2011,
        '2012': H19V08_2012, '2013': H19V08_2013, '2014': H19V08_2014, '2015': H19V08_2015,
        '2016': H19V08_2016, '2017': H19V08_2017, '2018': H19V08_2018, '2019': H19V08_2019}

H19V08_data = pd.DataFrame(data=columns)

In [21]:
H19V08_data

,latitude,longitude,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,10.0,10.15,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
1,10.0,10.15,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
2,10.0,10.15,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
3,10.0,10.15,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
4,10.0,10.15,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5759995,0.0,20.00,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759996,0.0,20.00,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759997,0.0,20.00,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759998,0.0,20.00,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759999,0.0,20.00,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104

In [41]:
np.savetxt("D:\\masters_data\\output\\csv\\Rainfall\\Trendmaps\\Complete_dataframes\\H19V08_rainfall_data.csv", H19V08_data, delimiter=",")

In [22]:
# Set input directory, and change working directory - plug in D:
inDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H20V07"  # I should change this so I can work from github?
os.chdir(inDir)  # Change to working directory
outDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H20V07" # Create and set output directory
if not os.path.exists(outDir): os.makedirs(outDir)
    
# select first rainfall file
H20V07_2002 = glob.glob('*2002*')
H20V07_2002 = pd.read_csv(H20V07_2002[0], header = None)
H20V07_2003 = glob.glob('*2003*')
H20V07_2003 = pd.read_csv(H20V07_2003[0], header = None)
H20V07_2004 = glob.glob('*2004*')
H20V07_2004 = pd.read_csv(H20V07_2004[0], header = None)
H20V07_2005 = glob.glob('*2005*')
H20V07_2005 = pd.read_csv(H20V07_2005[0], header = None)
H20V07_2006 = glob.glob('*2006*')
H20V07_2006 = pd.read_csv(H20V07_2006[0], header = None)
H20V07_2007 = glob.glob('*2007*')
H20V07_2007 = pd.read_csv(H20V07_2007[0], header = None)
H20V07_2008 = glob.glob('*2008*')
H20V07_2008 = pd.read_csv(H20V07_2008[0], header = None)
H20V07_2009 = glob.glob('*2009*')
H20V07_2009 = pd.read_csv(H20V07_2009[0], header = None)
H20V07_2010 = glob.glob('*2010*')
H20V07_2010 = pd.read_csv(H20V07_2010[0], header = None)
H20V07_2011 = glob.glob('*2011*')
H20V07_2011 = pd.read_csv(H20V07_2011[0], header = None)
H20V07_2012 = glob.glob('*2012*')
H20V07_2012 = pd.read_csv(H20V07_2012[0], header = None)
H20V07_2013 = glob.glob('*2013*')
H20V07_2013 = pd.read_csv(H20V07_2013[0], header = None)
H20V07_2014 = glob.glob('*2014*')
H20V07_2014 = pd.read_csv(H20V07_2014[0], header = None)
H20V07_2015 = glob.glob('*2015*')
H20V07_2015 = pd.read_csv(H20V07_2015[0], header = None)
H20V07_2016 = glob.glob('*2016*')
H20V07_2016 = pd.read_csv(H20V07_2016[0], header = None)
H20V07_2017 = glob.glob('*2017*')
H20V07_2017 = pd.read_csv(H20V07_2017[0], header = None)
H20V07_2018 = glob.glob('*2018*')
H20V07_2018 = pd.read_csv(H20V07_2018[0], header = None)
H20V07_2019 = glob.glob('*2019*')
H20V07_2019 = pd.read_csv(H20V07_2019[0], header = None)

In [23]:
# also need coordinates
H20V07_coordinates = pd.read_csv("D:\masters_data\output\csv\Rainfall\Rainfall_coordinates\H20V07.csv", header = None)
H20V07_latitude = H20V07_coordinates[0]
H20V07_longitude = H20V07_coordinates[1]

In [24]:
# 2002
H20V07_2002 = H20V07_2002.to_numpy()
H20V07_2002 = H20V07_2002.flatten().tolist()

# 2003
H20V07_2003 = H20V07_2003.to_numpy()
H20V07_2003 = H20V07_2003.flatten().tolist()

# 2004
H20V07_2004 = H20V07_2004.to_numpy()
H20V07_2004 = H20V07_2004.flatten().tolist()

# 2005
H20V07_2005 = H20V07_2005.to_numpy()
H20V07_2005 = H20V07_2005.flatten().tolist()

# 2006
H20V07_2006 = H20V07_2006.to_numpy()
H20V07_2006 = H20V07_2006.flatten().tolist()

# 2007
H20V07_2007 = H20V07_2007.to_numpy()
H20V07_2007 = H20V07_2007.flatten().tolist()

# 2008
H20V07_2008 = H20V07_2008.to_numpy()
H20V07_2008 = H20V07_2008.flatten().tolist()

# 2009
H20V07_2009 = H20V07_2009.to_numpy()
H20V07_2009 = H20V07_2009.flatten().tolist()

# 2010
H20V07_2010 = H20V07_2010.to_numpy()
H20V07_2010 = H20V07_2010.flatten().tolist()

# 2011
H20V07_2011 = H20V07_2011.to_numpy()
H20V07_2011 = H20V07_2011.flatten().tolist()

# 2012
H20V07_2012 = H20V07_2012.to_numpy()
H20V07_2012 = H20V07_2012.flatten().tolist()

# 2013
H20V07_2013 = H20V07_2013.to_numpy()
H20V07_2013 = H20V07_2013.flatten().tolist()

# 2014
H20V07_2014 = H20V07_2014.to_numpy()
H20V07_2014 = H20V07_2014.flatten().tolist()

# 2015
H20V07_2015 = H20V07_2015.to_numpy()
H20V07_2015 = H20V07_2015.flatten().tolist()

# 2016
H20V07_2016 = H20V07_2016.to_numpy()
H20V07_2016 = H20V07_2016.flatten().tolist()

# 2017
H20V07_2017 = H20V07_2017.to_numpy()
H20V07_2017 = H20V07_2017.flatten().tolist()

# 2011
H20V07_2018 = H20V07_2018.to_numpy()
H20V07_2018 = H20V07_2018.flatten().tolist()

# 2011
H20V07_2019 = H20V07_2019.to_numpy()
H20V07_2019 = H20V07_2019.flatten().tolist()

In [26]:
columns = {'latitude': H20V07_latitude, 'longitude': H20V07_longitude, '2002': H20V07_2002, '2003': H20V07_2003,
        '2004': H20V07_2004, '2005': H20V07_2005, '2006': H20V07_2006, '2007': H20V07_2007,
        '2008': H20V07_2008, '2009': H20V07_2009, '2010': H20V07_2010, '2011': H20V07_2011,
        '2012': H20V07_2012, '2013': H20V07_2013, '2014': H20V07_2014, '2015': H20V07_2015,
        '2016': H20V07_2016, '2017': H20V07_2017, '2018': H20V07_2018, '2019': H20V07_2019}

H20V07_data = pd.DataFrame(data=columns)

In [27]:
H20V07_data

,latitude,longitude,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,20.0,21.30,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
1,20.0,21.30,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
2,20.0,21.30,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
3,20.0,21.30,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
4,20.0,21.30,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5759995,10.0,30.45,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759996,10.0,30.45,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759997,10.0,30.45,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759998,10.0,30.45,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759999,10.0,30.45,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104

In [40]:
np.savetxt("D:\\masters_data\\output\\csv\\Rainfall\\Trendmaps\\Complete_dataframes\\H20V07_rainfall_data.csv", H20V07_data, delimiter=",")

In [29]:
# Set input directory, and change working directory - plug in D:
inDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H20V08"  # I should change this so I can work from github?
os.chdir(inDir)  # Change to working directory
outDir = "D:\masters_data\output\csv\Rainfall\Trendmaps\H20V08" # Create and set output directory
if not os.path.exists(outDir): os.makedirs(outDir)

In [30]:
# select first rainfall file
H20V08_2002 = glob.glob('*2002*')
H20V08_2002 = pd.read_csv(H20V08_2002[0], header = None)
H20V08_2003 = glob.glob('*2003*')
H20V08_2003 = pd.read_csv(H20V08_2003[0], header = None)
H20V08_2004 = glob.glob('*2004*')
H20V08_2004 = pd.read_csv(H20V08_2004[0], header = None)
H20V08_2005 = glob.glob('*2005*')
H20V08_2005 = pd.read_csv(H20V08_2005[0], header = None)
H20V08_2006 = glob.glob('*2006*')
H20V08_2006 = pd.read_csv(H20V08_2006[0], header = None)
H20V08_2007 = glob.glob('*2007*')
H20V08_2007 = pd.read_csv(H20V08_2007[0], header = None)
H20V08_2008 = glob.glob('*2008*')
H20V08_2008 = pd.read_csv(H20V08_2008[0], header = None)
H20V08_2009 = glob.glob('*2009*')
H20V08_2009 = pd.read_csv(H20V08_2009[0], header = None)
H20V08_2010 = glob.glob('*2010*')
H20V08_2010 = pd.read_csv(H20V08_2010[0], header = None)
H20V08_2011 = glob.glob('*2011*')
H20V08_2011 = pd.read_csv(H20V08_2011[0], header = None)
H20V08_2012 = glob.glob('*2012*')
H20V08_2012 = pd.read_csv(H20V08_2012[0], header = None)
H20V08_2013 = glob.glob('*2013*')
H20V08_2013 = pd.read_csv(H20V08_2013[0], header = None)
H20V08_2014 = glob.glob('*2014*')
H20V08_2014 = pd.read_csv(H20V08_2014[0], header = None)
H20V08_2015 = glob.glob('*2015*')
H20V08_2015 = pd.read_csv(H20V08_2015[0], header = None)
H20V08_2016 = glob.glob('*2016*')
H20V08_2016 = pd.read_csv(H20V08_2016[0], header = None)
H20V08_2017 = glob.glob('*2017*')
H20V08_2017 = pd.read_csv(H20V08_2017[0], header = None)
H20V08_2018 = glob.glob('*2018*')
H20V08_2018 = pd.read_csv(H20V08_2018[0], header = None)
H20V08_2019 = glob.glob('*2019*')
H20V08_2019 = pd.read_csv(H20V08_2019[0], header = None)

In [31]:
# also need coordinates
H20V08_coordinates = pd.read_csv("D:\masters_data\output\csv\Rainfall\Rainfall_coordinates\H20V08.csv", header = None)
H20V08_latitude = H20V08_coordinates[0]
H20V08_longitude = H20V08_coordinates[1]

In [32]:
# 2002
H20V08_2002 = H20V08_2002.to_numpy()
H20V08_2002 = H20V08_2002.flatten().tolist()

# 2003
H20V08_2003 = H20V08_2003.to_numpy()
H20V08_2003 = H20V08_2003.flatten().tolist()

# 2004
H20V08_2004 = H20V08_2004.to_numpy()
H20V08_2004 = H20V08_2004.flatten().tolist()

# 2005
H20V08_2005 = H20V08_2005.to_numpy()
H20V08_2005 = H20V08_2005.flatten().tolist()

# 2006
H20V08_2006 = H20V08_2006.to_numpy()
H20V08_2006 = H20V08_2006.flatten().tolist()

# 2007
H20V08_2007 = H20V08_2007.to_numpy()
H20V08_2007 = H20V08_2007.flatten().tolist()

# 2008
H20V08_2008 = H20V08_2008.to_numpy()
H20V08_2008 = H20V08_2008.flatten().tolist()

# 2009
H20V08_2009 = H20V08_2009.to_numpy()
H20V08_2009 = H20V08_2009.flatten().tolist()

# 2010
H20V08_2010 = H20V08_2010.to_numpy()
H20V08_2010 = H20V08_2010.flatten().tolist()

# 2011
H20V08_2011 = H20V08_2011.to_numpy()
H20V08_2011 = H20V08_2011.flatten().tolist()

# 2012
H20V08_2012 = H20V08_2012.to_numpy()
H20V08_2012 = H20V08_2012.flatten().tolist()

# 2013
H20V08_2013 = H20V08_2013.to_numpy()
H20V08_2013 = H20V08_2013.flatten().tolist()

# 2014
H20V08_2014 = H20V08_2014.to_numpy()
H20V08_2014 = H20V08_2014.flatten().tolist()

# 2015
H20V08_2015 = H20V08_2015.to_numpy()
H20V08_2015 = H20V08_2015.flatten().tolist()

# 2016
H20V08_2016 = H20V08_2016.to_numpy()
H20V08_2016 = H20V08_2016.flatten().tolist()

# 2017
H20V08_2017 = H20V08_2017.to_numpy()
H20V08_2017 = H20V08_2017.flatten().tolist()

# 2011
H20V08_2018 = H20V08_2018.to_numpy()
H20V08_2018 = H20V08_2018.flatten().tolist()

# 2011
H20V08_2019 = H20V08_2019.to_numpy()
H20V08_2019 = H20V08_2019.flatten().tolist()

In [37]:
columns = {'latitude': H20V08_latitude, 'longitude': H20V08_longitude, '2002': H20V08_2002, '2003': H20V08_2003,
        '2004': H20V08_2004, '2005': H20V08_2005, '2006': H20V08_2006, '2007': H20V08_2007,
        '2008': H20V08_2008, '2009': H20V08_2009, '2010': H20V08_2010, '2011': H20V08_2011,
        '2012': H20V08_2012, '2013': H20V08_2013, '2014': H20V08_2014, '2015': H20V08_2015,
        '2016': H20V08_2016, '2017': H20V08_2017, '2018': H20V08_2018, '2019': H20V08_2019}

H20V08_data = pd.DataFrame(data=columns)

In [38]:
H20V08_data

,latitude,longitude,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,10.0,20.3,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
1,10.0,20.3,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
2,10.0,20.3,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
3,10.0,20.3,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
4,10.0,20.3,775.723272,883.708000,820.543322,830.083057,888.339170,981.790888,930.094727,1003.597977,1022.365192,841.729464,928.039750,682.642556,868.693439,709.225158,815.802397,794.684584,758.186268,1194.678146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5759995,0.0,30.0,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759996,0.0,30.0,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759997,0.0,30.0,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759998,0.0,30.0,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104
5759999,0.0,30.0,1874.518847,1708.968444,1851.379734,1982.226258,1569.581024,2337.346222,1813.564301,1867.464314,2099.168995,2082.374471,1582.205118,1823.258219,1672.941996,1646.227833,1825.660017,2209.305540,2128.495622,2021.679104

In [39]:
np.savetxt("D:\\masters_data\\output\\csv\\Rainfall\\Trendmaps\\Complete_dataframes\\H20V08_rainfall_data.csv", H20V08_data, delimiter=",")

In [42]:
total_rainfall = H19V07_data.append(H19V08_data)
total_rainfall = total_rainfall.append(H20V07_data)
total_rainfall = total_rainfall.append(H20V08_data)

NameError: name 'H19V07_data' is not defined

In [ ]:
np.savetxt("D:\\masters_data\\output\\csv\\Rainfall\\Trendmaps\\Complete_dataframes\\Annual_rainfall.csv", total_rainfall, delimiter=",")

In [ ]:
total_rainfall